app/models/chat.py
from app.models.base_model import BaseModel, Base
from app.models.user import user_chat_association
from sqlalchemy import Column, String, Integer, ForeignKey, Boolean
from sqlalchemy.orm import relationship


"""
A chat is created for USER to USER conversations by the creator which is defined by creator_id
On creation the the recipient gets an additional chats in their invited_chats column
A chat therefore has several messages
A group cannot instanciate a chat
"""
class Chat(BaseModel, Base):
    __tablename__ = 'chats'
    is_groupchat = Column(Boolean, default=False, nullable=False)
    messages = relationship('Message', back_populates='chat')
    participants = relationship('User', secondary=user_chat_association, back_populates='chats', foreign_keys=[])
    
    # group_id = Column(String(60), ForeignKey('groups.id'), nullable=True)
    group = relationship('Group', back_populates='chat')

app/models/group.py
from app.models.base_model import Base, BaseModel
from sqlalchemy import Column, String, Table, ForeignKey, Integer
from sqlalchemy.orm import relationship
import app.models
from app.models.file import File
import os

# user_group_association = Table(
#     'user_group_association',
#     Base.metadata,
#     Column('user_id', String(60), ForeignKey('users.id'), primary_key=True, nullable=False),
#     Column('group_id', String(60), ForeignKey('user_groups.id'), primary_key=True, nullable=False),
#     Column('role', String(60), nullable=False, default='member'),
# )

class UserGroupAssociation(Base):
    __tablename__ = 'user_group_association'
    user_id = Column(String(60), ForeignKey('users.id'), primary_key=True)
    group_id = Column(String(60), ForeignKey('user_groups.id'), primary_key=True)
    role = Column(String(8), default='member')
    user = relationship("User", back_populates="group_associations", overlaps="admin_at,groups")
    group = relationship("Group", back_populates="user_associations", overlaps="admin_at, groups")

class Group(BaseModel, Base):
    __tablename__ = 'user_groups'
    _profilePic = Column(String(255), default='static/assets/groups/default-profile-pic.jpg', nullable=False)
    _coverPic = Column(String(255), default='static/assets/groups/default-cover-pic.jpg', nullable=False)
    name = Column(String(25), nullable=False)
    description = Column(String(128), nullable=False)
    
    chat_id = Column(String(60), ForeignKey('chats.id'))
    chat = relationship('Chat', back_populates='group')
    files = relationship('File', back_populates='group')
    
    user_associations = relationship('UserGroupAssociation', back_populates='group', cascade='all, delete-orphan', overlaps="admin_at,groups")
    members = relationship('User', secondary='user_group_association', back_populates='groups', 
                           primaryjoin="and_(UserGroupAssociation.group_id==Group.id, UserGroupAssociation.role=='member')", overlaps="admin_at, user, group, user_associations, group_associations")
    admins = relationship('User', secondary='user_group_association', back_populates='admin_at',
                          primaryjoin="and_(UserGroupAssociation.group_id==Group.id, UserGroupAssociation.role=='admin')",
                          overlaps="groups, members, user, group, user_associations, group_associations")
    
    def add_member(self, user, role='member'):
        if user not in self.members or user not in self.admins:
            association = UserGroupAssociation(user=user, group=self, role=role)
            self.user_associations.append(association)
            
    def promote_user(self, user):
        session = app.models.storage.get_session()
        association = session.query(UserGroupAssociation).filter_by(
            user_id = user.id, group_id = self.id).first()
        association.role = 'admin'
        session.commit()
        
    def demote_user(self, user):
        session = app.models.storage.get_session()
        association = session.query(UserGroupAssociation).filter_by(
            user_id = user.id, group_id = self.id).first()
        association.role = 'member'
        session.commit()
     
    @property
    def profilePic(self):
        return self._profilePic
    
    @profilePic.setter
    def profilePic(self, pic):
        if hasattr(pic, 'filename'):
            extension = os.path.splitext(pic.filename)[1]
            filename = 'profile-pic' + extension
        else:
            raise ValueError("Cannot parse given file")
        saved = self.uploadFile(pic, filename)
        if not isinstance(saved, File):
            raise ValueError("Error uploading profile picture")
        self._profilePic = os.path.join(saved.filepath, saved.filename)
        
    @property
    def coverPic(self):
        return self._coverPic
    
    @coverPic.setter
    def coverPic(self, pic):
        if hasattr(pic, 'filename'):
            extension = os.path.splitext(pic.filename)[1]
            filename = 'cover-pic' + extension
        else:
            raise ValueError("Cannot parse given file")
        saved = self.uploadFile(pic, filename)
        if not isinstance(saved, File):
            raise ValueError("Error uploading cover picture")
        self._coverPic = os.path.join(saved.filepath, saved.filename)
    
    def uploadFile(self, file, filename):
        print(filename)
        filedir = os.path.abspath(os.path.dirname(__file__))
        basedir = os.path.abspath(os.path.dirname(filedir))
        relative_path = f'static/assets/groups/{self.id}/shared'
        full_path = os.path.join(basedir, relative_path)
        if os.path.splitext(filename)[0] == 'profile-pic' or os.path.splitext(filename)[0] == 'cover-pic':
            relative_path = f'static/assets/groups/{self.id}/'
            full_path = os.path.join(basedir, relative_path)
        if not os.path.exists(full_path):
            os.makedirs(full_path)
        file.save(os.path.join(full_path, filename))
        saved_file = File(
            **{
                'filepath': relative_path,
                'filename': filename,
                'group': self,
            }
        )
        return saved_file
        
    def dp_path(self):
        file = app.models.storage.get('File', field='owner_id', value=self.id)
        

app/groups/forms.py
from wtforms import Form, StringField, validators, TextAreaField, FileField, SubmitField
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
    
class CreateGroupForm(Form):
    profilePic = FileField('Display Picture', validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'File format not allowed')])
    name = StringField('Group Name*', [validators.DataRequired(), validators.Length(min=4, max=25)])
    description = TextAreaField('Description (optional)', [validators.Length(max=255)])

    
class GroupUpdateForm(Form):
    pass

app/groups/__init__.py
from flask import Blueprint

groups = Blueprint('groups', __name__, url_prefix='/groups')

from .views import *

app/groups/views.py
from flask_login import login_required, current_user
from flask import make_response, request, redirect, flash, url_for, render_template
import requests, os
from werkzeug.utils import secure_filename

from . import groups
from app.models import storage
from app.models.group import Group, UserGroupAssociation
from .forms import CreateGroupForm, GroupUpdateForm

url = 'http://localhost:4000/api/v1'

DP_PATH = os.path.abspath(
    os.path.dirname(
        os.path.dirname(__file__)
    )
) + f'/static/icons/group.png'
UPDATEABLE_FIELDS = ['name', 'description', 'displayPic', 'coverPic']

@groups.route('/create', methods=['GET', 'POST'])
@login_required
def create_group():
    form = CreateGroupForm()
    if request.method == 'POST':
        data = {
            'name': request.form['name'],
            'description': request.form['description'],
        }
        profile_pic = request.files.get('profilePic')
        print(f"Type of profile_pic: {type(profile_pic)}")
        group = Group(**data)
        if profile_pic:
            group.profilePic = profile_pic
        group.add_member(current_user, role='admin')
        group.save()
        if storage.get('Group', group.id):
            next_page = request.args.get('next')
            if not next_page or not next_page.startswith('/'):
                next_page = f'/groups/{group.id}'
            flash('Group created successfully', category='message')
            return make_response(redirect(next_page))
        flash("Error creating group", category='error')
    return make_response(render_template('groups/create_group.html', form=form))

@groups.route('/groups')
def my_groups():
    return render_template('groups/groups_page.html')

@groups.route('/join/<group_id>')
@login_required
def join_group(group_id):
    group = storage.get('Group', group_id)
    if group is None:
        return make_response("Group not found"), 500
    user = current_user
    if user not in group.members:
        group.members.append(user)
        group.save()
        flash("You're now a member", category='message')
    else:
        flash("Already a member", category='error')
    next = request.args.get('next')
    if next is None or not next.startswith('/'):
        next = url_for('accounts.current_user_profile')
    return redirect(next)

@groups.route('/leave/<group_id>')
@login_required
def leave_group(group_id):
    group = storage.get('Group', group_id)
    if group is None:
        return make_response("Error while exiting group")
    group.members.remove(current_user)
    group.save()
    flash(f"You're no longer a member - {group.name}")
    next = request.args.get('next')
    if next is None or not next.startswith('/'):
        next = '/home'
    return make_response(redirect(next))

@groups.route('/<group_id>', methods=['GET'])
@login_required
def group_profile(group_id):
    group = storage.get('Group', group_id)
    # from app.models.chat import Chat
    # chat = Chat(is_groupchat=True)
    # chat.group.append(group)
    # chat.save()
    if group is not None:
        if current_user in group.members + group.admins:
            files = group.files
            members = group.admins + group.members
            profilePic = group.profilePic
            if group.chat:
                return make_response(redirect(f'/chats/{group.chat.id}'))
            return make_response(render_template('groups/group_profile.html',
                                                 group=group,
                                                 files=files,
                                                 members=members,
                                                 profilePic=profilePic
                                                 ))
        flash("You're not a member. Join group to view.", category='warn')
    next = request.args.get('next')
    if next is None or not next.startswith('/'):
        next = '/home'
    return make_response(redirect(next))

@groups.route('/delete/<group_id>')
@login_required
def delete_group(group_id):
    groups = storage.all('Group')
    for group in groups:
        group.delete()
        storage.save()
    flash("Group deleted successfully", category='error')
    next = request.args.get('next')
    if next is None or not next.startswith('/'):
        next = '/accounts/profile'
    return make_response(redirect(next))

@groups.route('<group_id>/settings', methods=['GET', 'PUT'])
@login_required
def group_settings(group_id):
    form = GroupUpdateForm()
    if request.method == 'PUT':
        group = storage.get('Group', group_id)
        if group:
            for key, val in request.form.to_dict():
                if key in UPDATEABLE_FIELDS:
                    setattr(group, key, val)
    return render_template('groups/settings.html')

app/templates/home/chats.html
<div id="chats-list" class="hidden flex flex-col items-center bg-white p-5 h-[100%] w-[100%] overflow-y-scroll">
	{% with chats = current_user.chats %}
	{% if chats %}
	{% for chat in chats %}
	<h1>{{chat}}</h1>
	{% endfor %}
	{% else %}
	<div class="flex flex-col items-center justify-center p-2">
		<a href="{{url_for('groups.create_group')}}" class="flex items-center p-2 bg-blue-200 rounded-md">
			<img class="w-[50px]  h-[50px] mx-2" src="../static/icons/group.png" alt="">
			<div class="flex flex-col items-center w-[100%] h-[100%]">
				<h1 class="text-lg font-bold">Start Conversation</h1>
				<h3 class="text-xs">Connect with peers</h3>
			</div>
		</a>
		<input class="border-2 h-[40px] p-2 outline-none" type="text" placeholder="Enter username...">
	</div>
	<details style="transition: .3s ease;" close class="flex flex-col w-[100%] border-t-2">
		<summary class="text-lg font-bold border-b-2 p-2 cursor-pointer">Suggestions</summary>
		<ul id="chat-suggestions" class="">
			{% for user in suggested_users %}
			{% if not user == current_user %}
			<li id="suggested-user.{{user.username}}" class="flex items-center border-b-2 hover:bg-gray-200 cursor-pointer">
					<img class="w-[50px] h-[50px] m-2" src="../{{user.profilePic}}" alt="">
					<h1>{{user.firstname}} {{user.lastname}}</h1>
			</li>
			{%endif%}
			{% endfor %}
		</ul>
	</div>
	{% endif %}
	{% endwith %}
</div>
<script>
	const suggestedUser = document.querySelectorAll('#chat-suggestion li')
	suggestedUser.addEventListener('click', () => {
		api = 'http://127.0.0.1:5000/api/v1/chats'
		$.get(api, {
			
		})
	})
</script>

app/templates/home/groups.html
<div id="groups-list" class="flex flex-col items-center bg-white p-5 h-[100%] w-[100%]">
	{% with groups = current_user.groups %}
	{% if groups %}
	<div class="flex flex-col w-[100%] h-[100%] items-center">
		<div class="flex grid grid-cols-10 items-center w-[100%] bg-gray-200">
			<h1 class="flex justify-center w-[100%] font-bold col-span-8">Groups</h1>
			<a class="flex items-center justify-center bg-blue-200 w-[fit-content] p-2 m-2 col-span-2 rounded-md text-center text-lg font-bold" href="/groups/create">
				<h1 class="md:hidden mx-2 text-3xl">+</h1><h1 class="hidden md:flex"> Create Group</h1>
			</a>
		</div>
		{% for group in groups %}
		<a href="{% if group.chat_id == None %}
					/groups/{{group.id}}
				{% else %}
					/chats/{{group.chat_id}}
				{% endif %}
				"
			class="flex border-b-2 w-[100%] hover:bg-gray-200 cursor-pointer">
			<img class="m-5 rounded-full" style="width: 50px; height: 50px;" src="../../{{group.profilePic}}" alt="">
			<div class="flex flex-col justify-center p-2">
				<h1>{{group.name}}</h1>
				<h3>~ {{group.description}}</h3>
			</div>
		</a>
		{% endfor %}
	</div>
	{% else %}
	<div class="flex flex-col items-center justify-center h-[100%]">
		<h1 class="p-2">You've not joined any groups</h1>
		<a href="{{url_for('groups.create_group')}}" class="flex items-center p-2 bg-blue-200 rounded-md">
			<img class="w-[50px]  h-[50px] mx-2" src="../static/icons/group.png" alt="">
			<div class="flex flex-col items-center w-[100%] h-[100%]">
				<h1 class="text-lg font-bold">Create Group</h1>
				<h3 class="text-xs">Connect with peers</h3>
			</div>
		</a>
		<h1>or</h1>
		<input class="border-2 h-[40px] p-2 outline-none" type="text" placeholder="Enter invite code...">
	</div>
	{% endif %}
	{% endwith %}
</div>